### ISSUE TITLE
Can't start the bot

### ISSUE THREAD

**Issue by Bluscream** [JABirchall/NimdaTS3#14]
```
blu@homeserver:/opt/nimbats3$ sudo php start.php
PHP Fatal error:  Uncaught PDOException: could not find driver in /opt/nimbats3/vendor/illuminate/database/Connectors/Connector.php:55
Stack trace:
#0 /opt/nimbats3/vendor/illuminate/database/Connectors/Connector.php(55): PDO->__construct('sqlite:/opt/nim...', NULL, NULL, Array)
#1 /opt/nimbats3/vendor/illuminate/database/Connectors/SQLiteConnector.php(37): Illuminate\Database\Connectors\Connector->createConnection('sqlite:/opt/nim...', Array, Array)
#2 /opt/nimbats3/vendor/illuminate/database/Connectors/ConnectionFactory.php(61): Illuminate\Database\Connectors\SQLiteConnector->connect(Array)
#3 [internal function]: Illuminate\Database\Connectors\ConnectionFactory->Illuminate\Database\Connectors\{closure}()
#4 /opt/nimbats3/vendor/illuminate/database/Connection.php(875): call_user_func(Object(Closure))
#5 /opt/nimbats3/vendor/illuminate/database/Connection.php(743): Illuminate\Database\Connection->getPdo()
#6 /opt/nimbats3/vendor/illuminate/database/Connection.php(628): Illuminate\Database\Connection->reconnectIfMissingConnect in /opt/nimbats3/vendor/illuminate/database/Connectors/Connector.php on line 55
```

**Comment by JABirchall** [comment]
You need to install sqlite

```apt-get install php-sqlite3```

**Comment by Bluscream** [comment]
Worked, thanks ^^
