### ISSUE TITLE
Opinion for Connection lost

### ISSUE THREAD

**Issue by HellBz** [JABirchall/NimdaTS3#32]
Last Time i got this:

```
connection to server '127.0.0.1:10011' lostPHP Fatal error:  Uncaught TeamSpeak3\Ts3Exception: connection to server '127.0.0.1:10011' lost in /PATHTOBOT/vendor/fkubis/teamspeak-php-framework/TeamSpeak3/Transport/TCP.php:136
Stack trace:
#0 /PATHTOBOT/vendor/fkubis/teamspeak-php-framework/TeamSpeak3/Adapter/ServerQuery.php(169): TeamSpeak3\Transport\TCP->readLine()
#1 /PATHTOBOT/app/TeamSpeak3Bot.php(253): TeamSpeak3\Adapter\ServerQuery->wait()
#2 /PATHTOBOT/app/TeamSpeak3Bot.php(203): App\TeamSpeak3Bot->wait()
#3 /PATHTOBOT/start.php(10): App\TeamSpeak3Bot->run()
#4 {main}
  thrown in /PATHTOBOT/vendor/fkubis/teamspeak-php-framework/TeamSpeak3/Transport/TCP.php on line 136
root@ks312952:/PATHTOBOT$ ^C
root@ks312952:/PATHTOBOT$ php start.php


```

Opinion for Reconnect or Else ??

**Comment by JABirchall** [comment]
There is no option to reconnect, As the if the server is offline there is too much variabilty to account for.
The only option is to be mindful of whether your server is offline and restart the bot after you have restarted your server.
