### ISSUE TITLE
Update in Server Query

### ISSUE THREAD

**Issue by HellBz** [JABirchall/NimdaTS3#38]
php start.php
[13:48:03]: Error 111: Connection refused
[13:48:03]: Error 111: Connection refused
[13:48:03]: Nimda finished total runtime: 0D 00:00:00 seconds, Using 355.15 KB memory.

**This is with new Libary:**
php start.php
PHP Fatal error:  Uncaught Error: Class 'TeamSpeak3\Helper\Profiler\Timer' not found in /home/users/hellbz/www/tsbot_hellbz_de/app/TeamSpeak3Bot.php:169
Stack trace:
#0 /home/users/hellbz/www/tsbot_hellbz_de/app/TeamSpeak3Bot.php(281): App\TeamSpeak3Bot->__construct('NIMDA', 'lpasswordhidden', '127.0.0.1', 10011, 'I-M-LIVE', 9987, 1)
#1 /home/users/hellbz/www/tsbot_hellbz_de/start.php(10): App\TeamSpeak3Bot::getInstance()
#2 {main}
  thrown in /home/users/hellbz/www/tsbot_hellbz_de/app/TeamSpeak3Bot.php on line 169

**Comment by HellBz** [comment]
I Create a Updated One, its working (Version 1.1.34)

https://packagist.org/packages/hellbz/teamspeak-php-framework
