### ISSUE TITLE
Issue when executing start.php

### ISSUE THREAD

**Issue by Polarcraft** [JABirchall/NimdaTS3#5]
antsbot@caveman-gaming:~/tsbot$ php composer.phar dump-autoload
Generating autoload files
antsbot@caveman-gaming:~/tsbot$ php start.php
PHP Fatal error:  Class 'Config\TeamSpeak' not found in /home/antsbot/tsbot/start.php on line 7
antsbot@caveman-gaming:~/tsbot$ php -v
PHP 5.5.9-1ubuntu4.19 (cli) (built: Jul 28 2016 19:31:33)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies

**Comment by JABirchall** [comment]
The minimum required php version is 5.6 as told in the readme: https://github.com/JABirchall/NimdaTS3/blob/master/README.md

**Comment by Polarcraft** [comment]
I just updated my version and I still get the same issue:

> antsbot@caveman-gaming:~/tsbot$ php composer.phar dump-autoload
Generating autoload files
antsbot@caveman-gaming:~/tsbot$ php start.php
PHP Fatal error:  Class 'Config\TeamSpeak' not found in /home/antsbot/tsbot/start.php on line 7
antsbot@caveman-gaming:~/tsbot$ php -v
PHP 5.6.23-1+deprecated+dontuse+deb.sury.org~trusty+1 (cli)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

**Comment by JABirchall** [comment]
Will look into it.

**Comment by JABirchall** [comment]
update, try the patch i just pushed

**Comment by Polarcraft** [comment]
Well that fixed that issue with it showing that error, but now I receive this issue:

> antsbot@caveman-gaming:~/tsbot$ php start.php
PHP Warning:  posix_getpwuid() expects exactly 1 parameter, 0 given in /home/antsbot/tsbot/app/TeamSpeak3Bot.php on line 139
[03:47:07]: [WARNING] Running Nimda logged in as serveradmin is bad!
[03:47:07]: Start anyway? Y/N: y
PHP Fatal error:  Uncaught exception 'PDOException' with message 'could not find driver' in /home/antsbot/tsbot/vendor/illuminate/database/Connectors/Connector.php:55
Stack trace:
#0 /home/antsbot/tsbot/vendor/illuminate/database/Connectors/Connector.php(55): PDO->__construct('sqlite:/home/an...', NULL, NULL, Array)
#1 /home/antsbot/tsbot/vendor/illuminate/database/Connectors/SQLiteConnector.php(37): Illuminate\Database\Connectors\Connector->createConnection('sqlite:/home/an...', Array, Array)
#2 /home/antsbot/tsbot/vendor/illuminate/database/Connectors/ConnectionFactory.php(61): Illuminate\Database\Connectors\SQLiteConnector->connect(Array)
#3 [internal function]: Illuminate\Database\Connectors\ConnectionFactory->Illuminate\Database\Connectors\{closure}()
#4 /home/antsbot/tsbot/vendor/illuminate/database/Connection.php(875): call_user_func(Object(Closure))
#5 /home/antsbot/tsbot/vendor/illuminate/database/Connection.php(743): Illuminate\Database\Connection->getPdo()
#6 /home/antsbot/tsbot/vendor/illuminate/database/Connection in /home/antsbot/tsbot/vendor/illuminate/database/Connectors/Connector.php on line 55
antsbot@caveman-gaming:~/tsbot$ php start.php
PHP Warning:  posix_getpwuid() expects exactly 1 parameter, 0 given in /home/antsbot/tsbot/app/TeamSpeak3Bot.php on line 139
[03:49:00]: [WARNING] Running Nimda logged in as serveradmin is bad!
[03:49:00]: Start anyway? Y/N: y
PHP Fatal error:  Class 'Plugin\Models\Plugin' not found in /home/antsbot/tsbot/app/TeamSpeak3Bot.php on line 300
antsbot@caveman-gaming:~/tsbot$

**Comment by JABirchall** [comment]
Ok im on track with what the issue is, I have now fixxed that error.

Since i dont have a linux dev environment there are some class autoloading case problems.

anyway try the latests patch

**Comment by Polarcraft** [comment]
Different issue now:
> antsbot@caveman-gaming:~/tsbot$ php start.php
[17:22:43]: [WARNING] Running Nimda logged in as serveradmin is bad!
[17:22:43]: Start anyway? Y/N: y
PHP Notice:  Trying to get property of non-object in /home/antsbot/tsbot/app/TeamSpeak3Bot.php on line 306
PHP Notice:  Trying to get property of non-object in /home/antsbot/tsbot/app/TeamSpeak3Bot.php on line 307
PHP Fatal error:  Call to a member function update() on null in /home/antsbot/tsbot/app/TeamSpeak3Bot.php on line 309

**Comment by JABirchall** [comment]
Ok try latest patch

**Comment by Polarcraft** [comment]
antsbot@caveman-gaming:~/tsbot$ php start.php
PHP Parse error:  syntax error, unexpected '->' (T_OBJECT_OPERATOR) in /home/antsbot/tsbot/app/TeamSpeak3Bot.php on line 304

**Comment by JABirchall** [comment]
ok try latest

**Comment by Polarcraft** [comment]
antsbot@caveman-gaming:~/tsbot$ php start.php
[18:46:20]: [WARNING] Running Nimda logged in as serveradmin is bad!
[18:46:20]: Start anyway? Y/N: y
PHP Notice:  Trying to get property of non-object in /home/antsbot/tsbot/app/TeamSpeak3Bot.php on line 304
PHP Notice:  Trying to get property of non-object in /home/antsbot/tsbot/app/TeamSpeak3Bot.php on line 305
PHP Fatal error:  Call to a member function update() on null in /home/antsbot/tsbot/app/TeamSpeak3Bot.php on line 307

**Comment by JABirchall** [comment]
I think you'll need to delete the Nimda database.sqlite and recreate it.

just run ```rm database.sqlite; touch database.sqlite``` because the code its breaking on is checking if the database is setup or if the database is failing. its getting none object error because the database is setup but contains nothing (related to nimda)

**Comment by Polarcraft** [comment]
Well when I try to run it with sqlite I get this:
PHP Fatal error:  Uncaught exception 'PDOException' with message 'could not find driver' in /home/antsbot/tsbot/vendor/illuminate/database/Connectors/Connector.php:55
Stack trace:
#0 /home/antsbot/tsbot/vendor/illuminate/database/Connectors/Connector.php(55): PDO->__construct('sqlite:/home/an...', NULL, NULL, Array)
#1 /home/antsbot/tsbot/vendor/illuminate/database/Connectors/SQLiteConnector.php(37): Illuminate\Database\Connectors\Connector->createConnection('sqlite:/home/an...', Array, Array)
#2 /home/antsbot/tsbot/vendor/illuminate/database/Connectors/ConnectionFactory.php(61): Illuminate\Database\Connectors\SQLiteConnector->connect(Array)
#3 [internal function]: Illuminate\Database\Connectors\ConnectionFactory->Illuminate\Database\Connectors\{closure}()
#4 /home/antsbot/tsbot/vendor/illuminate/database/Connection.php(875): call_user_func(Object(Closure))
#5 /home/antsbot/tsbot/vendor/illuminate/database/Connection.php(743): Illuminate\Database\Connection->getPdo()
#6 /home/antsbot/tsbot/vendor/illuminate/database/Connection in /home/antsbot/tsbot/vendor/illuminate/database/Connectors/Connector.php on line 55

**Comment by Polarcraft** [comment]
My fault was missing php5-sqlite, though I don't know if this is how it is supposed to look when starting up:

antsbot@caveman-gaming:~/tsbot$ php start.php
[19:24:20]: [WARNING] Running Nimda logged in as serveradmin is bad!
[19:24:20]: Start anyway? Y/N: y
[19:24:21]: Loading plugin [BadChannelName] by JABirchall                                                                                                                                                                                        :: Success.
[19:24:21]: Loading plugin [BadClass] by JABirchall                                                                                                                                                                                              :: Loading failed because class Plugin\BadClass doesn't exist.
[19:24:21]: Loading plugin [ChannelGroupNotifications] by JABirchall                                                                                                                                                                             :: Success.
[19:24:21]: Loading plugin [ClientInfo] by JABirchall                                                                                                                                                                                            :: Success.
[19:24:21]: Loading plugin [Jail] by JABirchall                                                                                                                                                                                                  :: Success.
[19:24:21]: Loading plugin [Kick] by JABirchall                                                                                                                                                                                                  :: Success.
[19:24:21]: Loading plugin [MD5] by JABirchall                                                                                                                                                                                                   :: Success.
[19:24:21]: Loading plugin [NoInterface] by JABirchall                                                                                                                                                                                           :: Loading failed because class Plugin\NoInterface does not impleme                                                                                                                                                    nt [PluginContract].
[19:24:21]: Loading plugin [Quotes] by JABirchall                                                                                                                                                                                                :: Install, Success.
[19:24:21]: Loading plugin [Seen] by JABirchall                                                                                                                                                                                                  :: Success.
[19:24:21]: Loading plugin [WelcomeMsg] by MAJID                                                                                                                                                                                                 :: Success.
[19:24:21]: Nimda version 0.10.0-alpha1 Started in 0.047 seconds, Using 4.02 MB                                                                                                                                                     memory.

**Comment by JABirchall** [comment]
Yes that is a successful launch.

**Comment by JABirchall** [comment]
This issue has been fixed, Thank you for your cooperation. If you encounter any other bugs do not hesitate to open a [new issue](issues/new)

**Comment by JABirchall** [comment]
This issue has been fixed, Thank you for your cooperation. If you encounter any other bugs do not hesitate to open a [new issue](new)

**Comment by JABirchall** [comment]
This is intended behaviour and will not be changed in the near future. If you have an idea for alternative methods please submit a [pull request](../../pull/new/master) for review.

**Comment by JABirchall** [comment]
This is intended behaviour and will not be changed in the near future. If you have an idea for alternative methods please submit a [pull request](../pull/new/master) for review.

**Comment by JABirchall** [comment]
This issue has been fixed, Thank you for your cooperation. If you encounter any other bugs do not hesitate to open a [new issue](new)
